# Site settings
title: Concise
email: contact@keenanpayne.com
description: "Concise is a lightweight front-end framework that provides a number of great features without the bloat."
author: "Keenan Payne"
host: localhost
port: 4000
baseurl: "/concise"
twitter_username: concisecss
github_username:  concisecss

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
